### ISSUE TITLE
Could not Generate Changelog

### ISSUE THREAD

**Issue by lisleyanne20** [metcalfc/changelog-generator#146]
Hi, 

I'm using this changelog generator and it works perfectly fine before but now I am getting this error: `Could not generate changelog between references because: The process '/home/runner/work/_actions/metcalfc/changelog-generator/v3.0.0/dist/changelog.sh' failed with exit code 128`

**Comment by metcalfc** [comment]
@lisleyanne20 thats is odd. I haven't made any changes in awhile. So something on the action side probably changed. Do you have a public action with logs I can look at?

**Comment by lisleyanne20** [comment]
@metcalfc I have used this on my workflow:
    - name: Generate changelog         
      id: changelog
      uses: metcalfc/changelog-generator@v3.0.0
      with:
        myToken: ${{ secrets.CHANGES_TOKEN }}
        head-ref: ${{github.sha}}
        base-ref: 'v2.0.57'
        reverse: 'true'

then I got the error. But when i removed the head and base ref, the error was gone.
