### ISSUE TITLE
[Recommendation]: Option to skip commit

### ISSUE THREAD

**Issue by tachibana-shin** [metcalfc/changelog-generator#165]
Hi,

I using this action for a monorepo

I like to skip some kind of commit such as `[mv2]: *` . This is necessary for monorepos because there are commits that are not related to each other.

**Comment by metcalfc** [comment]
Hi @tachibana-shin 

To keep this action simple the plan is just to list changes. That said actions itself is very flexible and you can post process the output. Here is an example that removes all the changes with `Bumping` in the text.
```
      - name: Modify the changelog
        id: modified
        run: |
          set -o noglob
          log=$(cat << "EOF" | grep -v Bumping | tac
          ${{ steps.changelog.outputs.changelog }}
          EOF
          )
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "log=$log" >> $GITHUB_OUTPUT
      - name: Print the modified changelog
        run: |
          cat << "EOF"
          ${{ steps.modified.outputs.log}}
          EOF
```
