### ISSUE TITLE
Commit hash as "view commit" link

### ISSUE THREAD

**Issue by thisdarktao** [metcalfc/changelog-generator#4]
Hey,

Would it be possible to have an input that allows us to use the shortened commit hash i.e. `dcb19ff` as the link to the commit itself?

It could be in the format:

```
[`dcb19ff`](example.com) - Commit message
```

Quite happy to make a PR if you don't have time to work on this?

**Comment by metcalfc** [comment]
Sure. I can try to get to it over the weekend. Or you can submit something and I’ll review it.

**Comment by metcalfc** [comment]
As I was thinking about it, I realized it was a two character change. So I just knocked it out really quick. You can find it here: https://github.com/metcalfc/changelog-generator/releases/tag/v0.3.0

Thanks for the suggestion. Hope you find the action useful.

**Comment by thisdarktao** [comment]
Hey, thanks for implementing this. Don't know if you noticed but the commit link had backticks in it so that the short commit hash would be monospace. No biggie though!

**Comment by metcalfc** [comment]
Fixed in [v0.3.2](https://github.com/metcalfc/changelog-generator/releases/tag/v0.3.2). Thanks for the suggest.
