### ISSUE TITLE
same error as issue #20 in version v0.4.4

### ISSUE THREAD

**Issue by sarnold** [metcalfc/changelog-generator#40]
In a repository with several (pre-release) tags I'm getting this:

```
  with:
    myToken: ***
  env:
    VERSION: 0.3.1-1
    pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.9/x64/lib
Error: Not Found
```
when trying to create a new release (not a pre-release) using github actions.  Looking at the closed bug I still can't figure out what the "correct" usage is.

**Comment by metcalfc** [comment]
Tags or actual GitHub release? They aren't treated the same in the GitHub API. If they are just tags, try turning the desired base into a release and see if that fixes the issue.

**Comment by sarnold** [comment]
It's a fork, and the previous "releases" are all tags.  They're obviously different "things" but github does show both releases and tags in the "release" column.  Anyway, I went ahead with a more flexible/forgiving solution using gitchangelog instead.  This seems like a good candidate for a readme update.

**Comment by metcalfc** [comment]
Thanks for the detail. Hopefully this #42 covers it.
