### ISSUE TITLE
insufficient permission for adding an object to repository database .git/objects

### ISSUE THREAD

**Issue by GabrielAcostaEngler** [metcalfc/changelog-generator#60]
When I try to run this action on one of our projects this is what I get. The same action works fine on our other project, does anyone know why that is?

![image](https://user-images.githubusercontent.com/31413261/113706563-1f2f5080-96df-11eb-8736-f496e3bccf1b.png)

**Comment by metcalfc** [comment]
I think it has to do with how the code is checked out and not this action.

I haven't seen this but folks have seen some issues with action checkouts. It really depends on how the repo was checked out and by who. Did you use the checkout action? 

Here is a thread where folks worked through a similar issue. https://github.com/actions/checkout/issues/164
