### ISSUE TITLE
github release creates a tag on publish

### ISSUE THREAD

**Issue by rchincha** [metcalfc/changelog-generator#96]
Trying to integrate your changelog generator workflow into:
https://github.com/anuvu/zot

However, the workflow breaks like so:
https://github.com/anuvu/zot/runs/4215543984?check_suite_focus=true

As part of github release, github insists on creating a new tag and this appears to confuse this workflow. Should `base-ref` be set to the previous tag instead of latest tag? Maybe I am just using this workflow incorrectly.

**Comment by metcalfc** [comment]
This is the way to use it by default:

```
- name: Generate changelog
  id: changelog
  uses: metcalfc/changelog-generator@v1.0.0
  with:
    myToken: ${{ secrets.GITHUB_TOKEN }}
```

This automatically moves the changelog between the point and time you run the action and the last release. The action assumes that you have created a real GitHub release and not just a tag.

You can also use the action to generate notes between any valid reference (hash, tag, branch, whatever). You just have to update the workflow somehow to do that. 

My project flow is make updates. `npm version patch` and that generates a release. As part of that it generates the new notes.  Here is the workflow:

https://github.com/metcalfc/changelog-generator/blob/main/.github/workflows/release.yml

You'll see that I generate the notes and then create a GitHub release. So the notes get calculated between the last release and right before I create the next release.

**Comment by metcalfc** [comment]
Thanks for checking out the action. I hope the default does what you need. I'll close this for now. Feel free to reopen if there is something about this action that the built in doesn't handle.
